compose_schema_version: "3"

containers:
  - service_name: prometheus
    active: true
    image: prom/prometheus:v2.55.1@sha256:2659f4c2ebb718e7695cb9b25ffa7d6be64db013daba13e05c875451cf51b0d3
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    user: 1000:1000
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom_data:/prometheus
    networks:
      - default

  - service_name: grafana
    active: true
    image: grafana/grafana@sha256:83749231c3835e390a3144e5e940203e42b9589761f20ef3169c716e734ad505
    container_name: grafana
    user: 1000:1000
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD={{ gf_admin_password }}
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - default

  - service_name: node_exporter
    active: true
    image: quay.io/prometheus/node-exporter:latest@sha256:2f0cc335ef9ea15d6c96e1c0d693d8b57c0b794d0244b22313a6c162bd1cb1b8
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    privileged: true
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - default

  - service_name: cadvisor
    active: true
    image: gcr.io/cadvisor/cadvisor@sha256:3de2bd5203120b866d74a9b283b2ffb8ec382fbf9dc321814700c6ea6f44ec57
    devices:
      - /dev/kmsg
    privileged: true
    container_name: cadvisor
    volumes:
      - '/dev/disk/:/dev/disk:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/sys:/sys:ro'
      - '/var/run:/var/run:ro'
      - '/:/rootfs:ro'
    networks:
      - default

  - service_name: influxdb
    active: false
    image: influxdb:2.8.0@sha256:96410d41a98c02fa5fcddc44cf708e297c8afcf02cd5bb6c620d4ae6a6d12390
    container_name: influxdb
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 8087:8086
    volumes:
      - './influxdb:/var/lib/influxdb2'
    environment:
      - 'DOCKER_INFLUXDB_INIT_USERNAME=admin'
      - 'DOCKER_INFLUXDB_INIT_PASSWORD={{ influxdb_password }}'
      - 'DOCKER_INFLUXDB_INIT_ORG={{ influxdb_org }}'
      - 'DOCKER_INFLUXDB_INIT_BUCKET={{ influxdb_bucket }}'
    default:
      - default

networks:
  - network_name: default

volumes: []
