compose_schema_version: "3"

containers:
  - service_name: prometheus
    active: true
    image: prom/prometheus:v3.11.3@sha256:e4254400b85610324913f0dc4acf92603d9984e7519414c5a12811aa6146acc3
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    user: 1000:1000
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prom_data:/prometheus
    networks:
      - default

  - service_name: grafana
    active: true
    image: grafana/grafana@sha256:0f86bada30d65ef9d0183b90c1e2682ac92d53d95da8bed322b984ea78a4a73a
    container_name: grafana
    user: 1000:1000
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD={{ gf_admin_password }}
    volumes:
      - ./grafana:/var/lib/grafana
    networks:
      - default

  - service_name: node_exporter
    active: true
    image: quay.io/prometheus/node-exporter:latest@sha256:0f422f62c15f154af8d8572b23d623aebfb10cec73a5c654d18f911f3f9df241
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    privileged: true
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
    networks:
      - default

  - service_name: cadvisor
    active: true
    image: gcr.io/cadvisor/cadvisor@sha256:3de2bd5203120b866d74a9b283b2ffb8ec382fbf9dc321814700c6ea6f44ec57
    devices:
      - /dev/kmsg
    privileged: true
    container_name: cadvisor
    volumes:
      - '/dev/disk/:/dev/disk:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
      - '/sys:/sys:ro'
      - '/var/run:/var/run:ro'
      - '/:/rootfs:ro'
    networks:
      - default

  - service_name: influxdb
    active: false
    image: influxdb:2.8.0@sha256:71f2bce68b47a3e26c1ed38f7480a9372b008ba9b7c8a35cb2c913d3102d377f
    container_name: influxdb
    user: 1000:1000
    restart: unless-stopped
    ports:
      - 8087:8086
    volumes:
      - './influxdb:/var/lib/influxdb2'
    environment:
      - 'DOCKER_INFLUXDB_INIT_USERNAME=admin'
      - 'DOCKER_INFLUXDB_INIT_PASSWORD={{ influxdb_password }}'
      - 'DOCKER_INFLUXDB_INIT_ORG={{ influxdb_org }}'
      - 'DOCKER_INFLUXDB_INIT_BUCKET={{ influxdb_bucket }}'
    default:
      - default

networks:
  - network_name: default

volumes: []
