---
compose_schema_version: '3'

containers:
  - service_name: homeassistant
    active: true
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:572a5d030f652e9ef6c6d4f6631169af83eb3b739c9b4b3965669f5e9d9f3858"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - GUID=1000

networks: []

volumes: []