---
compose_schema_version: '3'

containers:
  - service_name: homeassistant
    active: true
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:ae0800c81fea16bc1241ce03bddb9c6260566e90f58b09d3e5a629e4f68bdc0b"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - GUID=1000

networks: []

volumes: []