---
compose_schema_version: '3'

containers:
  - service_name: homeassistant
    active: true
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable@sha256:0e091dfce3068339c3e1d14382e6c34141e05cd589a1972ebd4d9a8e6b5d8969"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    environment:
      - PUID=1000
      - GUID=1000

networks: []

volumes: []