compose_schema_version: '3.9'
containers:
    - service_name: agent
      active: true
      image: 'portainer/agent:2.40.0@sha256:956f99ebb48840b7cbe502b340be1fd2bb334b2ed357663cb274d7f9f8a75911'
      volumes:
          - '/var/lib/docker/volumes:/var/lib/docker/volumes'
          - '/var/run/docker.sock:/var/run/docker.sock'
      restart: always
      container_name: portainer_agent
      ports:
          - '9001:9001'

networks: []
volumes: []
