compose_schema_version: '3.2'
containers:
  - service_name: postgres
    active: true
    image: postgres:16.13-bookworm@sha256:3daa88ea6b4f430fa93bec541be8e295f021bb399929d75d2b768d8b9778f7cd
    restart: unless-stopped
    container_name: postgres
    user: 1000:1000
    networks:
      - backend
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD={{ pg_password}}"

networks:
  - network_name: backend
    external: true

volumes: []