compose_schema_version: '3.2'
containers:
  - service_name: postgres
    active: true
    image: postgres:16.13-bookworm@sha256:6fd027a9c72f0fac7bcc53877098e1c9c9ab291fd7fbca24d0f8d4c988c5a580
    restart: unless-stopped
    container_name: postgres
    user: 1000:1000
    networks:
      - backend
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD={{ pg_password}}"

networks:
  - network_name: backend
    external: true

volumes: []