compose_schema_version: '3.2'
containers:
  - service_name: postgres
    active: true
    image: postgres:16.12-bookworm@sha256:31424d3261c4ba75df1fca72d44f6842b66ce4ec76c1a4685f7a7219f6ec8924
    restart: unless-stopped
    container_name: postgres
    user: 1000:1000
    networks:
      - backend
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD={{ pg_password}}"

networks:
  - network_name: backend
    external: true

volumes: []